# Generated by Django 3.1.6 on 2021-02-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
